#!/bin/sh

# getmap 
# bash script to download a map
# filename=$1     uncomment/replace this line for interactive use....
#
#
filename=$MAPNOWFILENAME
url=ftp://ftp.maps.canada.ca/pub/nrcan_rncan/raster/topographic/250k/

if [ -z "$filename" ]
then
      echo "no filename specified"
      echo "retry using template..."
      echo "getmap 031e_0300_canmatrix_prttif.zip"
      exit 1
else
      echo " downloading $filename "
fi
subdir1="$(echo $filename | cut -c -3)"
subdir2="$(echo $filename | cut -c 4)"
dir="$url$subdir1/$subdir2/$filename"
echo $dir

echo "finished script - getting map"


#  wget ftp://ftp.maps.canada.ca/pub/nrcan_rncan/raster/topographic/50k/117/d/03/117d03_e_0100_canmatrix_prttif.zip

wget --show-progress --directory-prefix=../../../3raw/   $dir
echo "wget exit code is"
echo $?
if [ $? -ne 0 ]
then
      echo " "
      echo "Download failed - wget error code was"
      echo $? 
      exit 1
fi  
cd ../../../3raw
unzip *.zip
rm *.zip
rm *.xml
echo " "
echo "map saved in data/share/oz3/Canada/topographic/maps/250k/3raw/$filename"
